//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlineReservationApp.BookingService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FlightSeatInfo", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class FlightSeatInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AirlineReservationApp.BookingService.SeatClass SeatClassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[][] SeatMatrixField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AirlineReservationApp.BookingService.SeatClass SeatClass {
            get {
                return this.SeatClassField;
            }
            set {
                if ((this.SeatClassField.Equals(value) != true)) {
                    this.SeatClassField = value;
                    this.RaisePropertyChanged("SeatClass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[][] SeatMatrix {
            get {
                return this.SeatMatrixField;
            }
            set {
                if ((object.ReferenceEquals(this.SeatMatrixField, value) != true)) {
                    this.SeatMatrixField = value;
                    this.RaisePropertyChanged("SeatMatrix");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SeatClass", Namespace="http://schemas.datacontract.org/2004/07/Enum")]
    public enum SeatClass : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FirstClass = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Economy = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BookingDetailRequest", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class BookingDetailRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AirlineReservationApp.BookingService.BookingDetailDao BookingDetailDaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AirlineReservationApp.BookingService.BookingDetailDao BookingDetailDao {
            get {
                return this.BookingDetailDaoField;
            }
            set {
                if ((object.ReferenceEquals(this.BookingDetailDaoField, value) != true)) {
                    this.BookingDetailDaoField = value;
                    this.RaisePropertyChanged("BookingDetailDao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BookingDetailDao", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class BookingDetailDao : AirlineReservationApp.BookingService.SeatPositionDao {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid CustomerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid FlightIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid CustomerId {
            get {
                return this.CustomerIdField;
            }
            set {
                if ((this.CustomerIdField.Equals(value) != true)) {
                    this.CustomerIdField = value;
                    this.RaisePropertyChanged("CustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid FlightId {
            get {
                return this.FlightIdField;
            }
            set {
                if ((this.FlightIdField.Equals(value) != true)) {
                    this.FlightIdField = value;
                    this.RaisePropertyChanged("FlightId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SeatPositionDao", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AirlineReservationApp.BookingService.BookingDetailDao))]
    public partial class SeatPositionDao : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AirlineReservationApp.BookingService.SeatClass ClassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short SeatColField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short SeatRowField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AirlineReservationApp.BookingService.SeatClass Class {
            get {
                return this.ClassField;
            }
            set {
                if ((this.ClassField.Equals(value) != true)) {
                    this.ClassField = value;
                    this.RaisePropertyChanged("Class");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short SeatCol {
            get {
                return this.SeatColField;
            }
            set {
                if ((this.SeatColField.Equals(value) != true)) {
                    this.SeatColField = value;
                    this.RaisePropertyChanged("SeatCol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short SeatRow {
            get {
                return this.SeatRowField;
            }
            set {
                if ((this.SeatRowField.Equals(value) != true)) {
                    this.SeatRowField = value;
                    this.RaisePropertyChanged("SeatRow");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://AirplaneReservationLib", ConfigurationName="BookingService.IBookingService")]
    public interface IBookingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://AirplaneReservationLib/IBookingService/RetrieveOccupiedSeatsMatrixFromFlig" +
            "htId", ReplyAction="http://AirplaneReservationLib/IBookingService/RetrieveOccupiedSeatsMatrixFromFlig" +
            "htIdResponse")]
        AirlineReservationApp.BookingService.FlightSeatInfo[] RetrieveOccupiedSeatsMatrixFromFlightId(System.Guid flightId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://AirplaneReservationLib/IBookingService/RetrieveOccupiedSeatsMatrixFromFlig" +
            "htId", ReplyAction="http://AirplaneReservationLib/IBookingService/RetrieveOccupiedSeatsMatrixFromFlig" +
            "htIdResponse")]
        System.Threading.Tasks.Task<AirlineReservationApp.BookingService.FlightSeatInfo[]> RetrieveOccupiedSeatsMatrixFromFlightIdAsync(System.Guid flightId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://AirplaneReservationLib/IBookingService/BookTicket", ReplyAction="http://AirplaneReservationLib/IBookingService/BookTicketResponse")]
        string BookTicket(AirlineReservationApp.BookingService.BookingDetailRequest bookingDetail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://AirplaneReservationLib/IBookingService/BookTicket", ReplyAction="http://AirplaneReservationLib/IBookingService/BookTicketResponse")]
        System.Threading.Tasks.Task<string> BookTicketAsync(AirlineReservationApp.BookingService.BookingDetailRequest bookingDetail);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBookingServiceChannel : AirlineReservationApp.BookingService.IBookingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BookingServiceClient : System.ServiceModel.ClientBase<AirlineReservationApp.BookingService.IBookingService>, AirlineReservationApp.BookingService.IBookingService {
        
        public BookingServiceClient() {
        }
        
        public BookingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BookingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AirlineReservationApp.BookingService.FlightSeatInfo[] RetrieveOccupiedSeatsMatrixFromFlightId(System.Guid flightId) {
            return base.Channel.RetrieveOccupiedSeatsMatrixFromFlightId(flightId);
        }
        
        public System.Threading.Tasks.Task<AirlineReservationApp.BookingService.FlightSeatInfo[]> RetrieveOccupiedSeatsMatrixFromFlightIdAsync(System.Guid flightId) {
            return base.Channel.RetrieveOccupiedSeatsMatrixFromFlightIdAsync(flightId);
        }
        
        public string BookTicket(AirlineReservationApp.BookingService.BookingDetailRequest bookingDetail) {
            return base.Channel.BookTicket(bookingDetail);
        }
        
        public System.Threading.Tasks.Task<string> BookTicketAsync(AirlineReservationApp.BookingService.BookingDetailRequest bookingDetail) {
            return base.Channel.BookTicketAsync(bookingDetail);
        }
    }
}
